### PR TITLE
fix resize issue and commit the dist

### PR DESCRIPTION
**Pull request by clevett**
* Fix resize issue

### CODE REVIEW

**Comment by arranf** [comment]
Want to flag that this is a problem I've run into as well. Would be keen to get this merged into mainline!

**Review by frankieali — COMMENTED** [review]
Why are you committing the build files in the dist folder? Those are not necessary for source control.

**Review by frankieali — COMMENTED** [review]
Man, the whitespace changes are driving me nuts. Do you have a beautifier/prettier config file you could include? I think I'll make a new branch and apply the beautifier formatting. It'll smooth out this PR process.

**Comment by clevett** [comment]
Sorry. I should have replied to this soon.  I'll close this PR as the code that fix this is found in the issue #54

**Pull request closed without merging**
