### PR TITLE
Added OnCollision callback

### PR DESCRIPTION
**Pull request by fazriz**
Added a OnCollision callback, this is useful if someone wants to see collision to add sound logic to their rolls.

### CODE REVIEW

**Comment by raymondtri** [comment]
awesome addition, would love to see this merged

**Comment by frankieali** [comment]
Looks good to me. Thanks for adding this feature.

**Comment by moficodes** [comment]
@frankieali Any chance of releasing a patch version of Dice-box with this change?

**Comment by mikaelmattsson** [comment]
How do I use this? Latest version on npm doesn't seem to have this code.

**Pull request merged**
