### PR TITLE
Add the ability to use a seeded PRNG in the Physics Engine

### PR DESCRIPTION
**Pull request by cthos**
Testing out the idea I had over in #47 on the source repo, I've added some code which makes the random number generator in the physics worker deterministic.

Here's what I've determined so far:

* Fixed canvas sizes do not impact the simulation, even if those canvases are of different sizes.
* Display resolution does not impact the simulation.
* Making the canvas the same size as the viewport (to toss dice on top of the whole page, for example) _does_ impact the simulation when you change the viewport size quite drastically.
* Changing the _scale_ of the dice does impact the physics (which makes sense, though for my case of synching clients, I don't think there's a case where you'd have different scales on different clients).
* _Sometimes_ something goes sideways and 2 canvas elements that are otherwise identical do not produce the same results. It's the same probably about 70% of the time, and I'm thinking it has something to do with either the timing on the main loop, something weird happening with floating point math, or some randomness in the rigidbody physics (somewhere in Ammo that I likely won't be able to get to).
* Interestingly, the _first_ roll after the world is initialized is _always_ identical for a given seed - I've not been able to get it to give different results right after initialization.

### CODE REVIEW

**Comment by frankieali** [comment]
> Interestingly, the first roll after the world is initialized is always identical for a given seed - I've not been able to get it to give different results right after initialization.

I don't quite understand this point. You want to duplicate the roll right? Are you saying that duplicate rolls seem to work best right after initialization, but after that they deviate?

**Comment by cthos** [comment]
> I don't quite understand this point. You want to duplicate the roll right? Are you saying that duplicate rolls seem to work best right after initialization, but after that they deviate?

Yeah, exactly - right after the canvas is initialized and the roll is triggered, the physics simulation seems very consistent and will constantly produce the same results (assuming the scene / dice / etc are all the same size). 

After that if you have 2 instances, with the same seed, rolling at the same time - sometimes the results will differ. The dice will start in the same position, but they'll land differently. If you're curious I can do a quick screen recording to illustrate what I'm seeing.

**Comment by cthos** [comment]
Ohhhhh, I'm getting pretty sure that this is related to the simulation clock continuing to run, because if you trigger rolls at different times, the rolls will differ from previous iterations, even if the instances running side-by-side are producing the same results.

I may just wait until you all have sorted providing absolute values to the dice rolls, as controlling for clock drift is going to be a huuuuge pain 🤔 

(on the other hand, I'm having fun futzing with this and it ....may.... still be useful for unit / feature testing).

**Comment by cthos** [comment]
So here are some illustrations demonstrating the problem:
I've essentially got 2 simulations running side-by-side with the same seed. The console is spitting out the RNG numbers for the inputs and they're the same for each of the rolls. There's a timeout running every 3000 ms, which triggers the `.roll` on both elements.

This screenshot is from a run where everything was proceeding apace for the majority of the run:
Screenshot from 2022-07-24 17-54-59

However this subsequent run (just the list of results) was much less accurate:
Screenshot from 2022-07-24 17-53-37

And you'll note that the rolls themselves don't line up to the previous run (some do, for example, the 6th roll was the same), except for the very first roll.

And a video of the thing in action: https://youtu.be/Np7K4R4d9ww

**Comment by cthos** [comment]
Yeah, I'm not going to futz with this much more, so closing the PR 👍🏻

**Pull request closed without merging**
